name: epo-data
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1
  - dogpile.cache=1.1.4
  - imageio=2.9
  - jupyter
  - matplotlib=3.4.3
  - numpy=1.21.3
  - pandas
  - pillow=8.3.2
  - pip
  - python=3.9.7
  - pytorch=1.10.0
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - tqdm=4.62
  - pip:
    - clip==1.0
    - regex
    - sentence-transformers==2.1
    - sentencepiece==0.1.96
    - tokenizers==0.10
    - transformers==4.13
